Change repo structure, add workflow for scattering many files and add cwltests
EBI-Metagenomics/CRISPRCasFinder-CWL pull request #1
Opened 2022-07-12 15:43 UTC by Vkale1

2022-07-12 19:04 UTC, caballero commented on src/workflows/runCRISPRCasFinderl.cwl
> -    default: "CRISPRCasFinder.gff3"
if there are no defaults, the value should be enforced by removing "?" from the type definition

2022-07-12 19:04 UTC, caballero commented on src/workflows/runCRISPRCasFinderl.cwl
> -    default: "CRISPRCasFinder_Spacers.fasta"
if there are no defaults, the value should be enforced by removing "?" from the type definition

2022-07-12 19:08 UTC, caballero requested changes
minor comments on removing defaults, almost all changes are fine

2022-07-13 06:59 UTC, Vkale1 commented on src/workflows/runCRISPRCasFinderl.cwl
> -    default: "CRISPRCasFinder_Spacers.fasta"
Removed input for both in new commit as it's not required anymore. These string defaults are now defined in the separate tool cwls.

2022-07-13 08:51 UTC, mberacochea commented on tests/tests.yml
> +      #no checksum as file has date run at the start
Use `Any` instead

2022-07-13 08:51 UTC, mberacochea commented on .github/workflows/test.yml
> +name: Testing
Very nice :1st_place_medal:

2022-07-13 08:54 UTC, mberacochea commented on src/workflows/runCRISPRCasFinderl_array.cwl
> +    type: string?
This one could be an Enum instead -> https://www.commonwl.org/user_guide/misc/#enum-inputs

2022-07-13 08:56 UTC, mberacochea commented on src/workflows/runCRISPRCasFinderl_array.cwl
> +        casDefinition: casDefinition
We should try to keep the naming consistent:
`casDefinition` and then the outputs are `crisprcasfinder_fasta`
I would go with `cas_definition`

2022-07-13 08:57 UTC, mberacochea approved these changes
Great stuff! I've added some minor comments, but it looks great :).

Thank you for making the repo "compliant" with the team conventions.

2022-07-13 18:45 UTC, merged